default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_app_development
  username: restaurant
  password: Llatrese34

test:
  <<: *default
  database: restaurant_app_test
  username: restaurant
  password: Llatrese34

production:
  <<: *default
  database: restaurant_app_production
  username: restaurant_app
  password: <%= ENV['RESTAURANT_APP_DATABASE_PASSWORD'] %>
